spring:
 datasource:
  url: jdbc:oracle:thin:@localhost:1521/orclpdb
  username: testuser
  password: testuser
  driverClassName: oracle.jdbc.driver.OracleDriver

  thymeleaf:
   cache: false

mybatis:
  mapper-locations: classpath*:/mappers/*.xml